import { defineConfig } from 'tsup';

export default defineConfig({
  entry: {
    'providers/transport': 'src/providers/transport.ts',
    'configuration/credential-client': 'src/configuration/credential-client.ts',
    'configuration/credential-sharing': 'src/configuration/credential-sharing.ts',
    'configuration/owned-credentials': 'src/configuration/owned-credentials.ts',
    'providers/service-validation': 'src/providers/service-validation.ts',
    'providers/catalog': 'src/providers/catalog.ts',
    'runtime/cli': 'src/runtime/cli.ts',
    'runtime/semaphore': 'src/runtime/semaphore.ts',
    'runtime/outbox': 'src/runtime/outbox.ts',
    'runtime/task-loop': 'src/runtime/task-loop.ts',
    'runtime/stream': 'src/runtime/stream.ts',
    'runtime/request': 'src/runtime/request.ts',
    'runtime/process': 'src/runtime/process.ts',
    'runtime/environment': 'src/runtime/environment.ts',
    'runtime/ssh': 'src/runtime/ssh.ts',
    'storage/index': 'src/storage/index.ts',
    'storage/optimistic': 'src/storage/optimistic.ts',
    'storage/sql': 'src/storage/sql.ts',
    'storage/instance': 'src/storage/instance.ts',
    'observability/index': 'src/observability/index.ts',
    'observability/store': 'src/observability/store.ts',
    'observability/pricing': 'src/observability/pricing.ts',
    'configuration/index': 'src/configuration/index.ts',
    'ai/index': 'src/ai/index.ts',
    'ai/google': 'src/ai/google.ts',
    'ai/catalog': 'src/ai/catalog.ts',
    'ai/providers': 'src/ai/providers.ts',
    'ai/connection': 'src/ai/connection.ts',
    'ai/usage': 'src/ai/usage.ts',
    'ai/tools': 'src/ai/tools.ts',
    'ai/openai-compatible': 'src/ai/openai-compatible.ts',
    'ai/anthropic': 'src/ai/anthropic.ts',
    'ai/openai-responses': 'src/ai/openai-responses.ts',
    'ai/browser': 'src/ai/browser.ts',
    'access/index': 'src/access/index.ts',
    'access/http': 'src/access/http.ts',
    'access/browser': 'src/access/browser.ts',
    'setup/index': 'src/setup/index.ts',
    'notifications/index': 'src/notifications/index.ts',
  },
  format: ['esm', 'cjs'],
  target: 'node22',
  external: ['thesidedoor-flock'],
  dts: true,
  clean: true,
  treeshake: true,
});
